### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by fprl** [opennextjs/opennextjs-cloudflare#42] opened 2024-09-26 20:30 UTC
Hi, thank you for working on this.

I can't build my app. This is my `wrangler.toml`:
```toml
name = "project"
main = ".worker-next/index.mjs"

compatibility_date = "2024-08-29"
compatibility_flags = ["nodejs_compat_v2"]

assets = { directory = ".worker-next/assets", binding = "ASSETS" }
```

This is what I get after running the command `"build:worker": "cloudflare"` (the project is built and I get to see the summary of the routes in the terminal)
```
○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand

⚙️ Copying files...

# copyPackageTemplateFiles
⚙️ Bundling the worker file...

# patchWranglerDeps
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open 
'project/apps/web/.worker-next/.next/standalone/apps/web/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js'

Node.js v22.0.0
```

As expected, there is no file under that directory
<img width="312" alt="image" src="https://github.com/user-attachments/assets/42907f39-84b1-424f-8429-99f634e65a38">

**Comment by datagutt** [comment] 2024-09-26 21:45
Also experiencing this, both with Next 14 and 15 (not exactly un-expected).

**Comment by jasonsilberman** [comment] 2024-09-30 15:43
Seeing this same error with Next 13.4.19. Really excited to try this out but this is a pretty hard blocker at the moment! Fwiw I'm using `yarn` and saw this pr (https://github.com/opennextjs/opennextjs-cloudflare/pull/49), so might wait until that gets merged to try again.

**Comment by jasonsilberman** [comment] 2024-09-30 18:52
Hi, I tried again after https://github.com/opennextjs/opennextjs-cloudflare/pull/49 got merged and I am still seeing this error.

**Comment by vacom** [comment] 2024-09-30 20:00
I was waiting for the issue https://github.com/opennextjs/opennextjs-cloudflare/issues/45 I opened on Yarn and now I'm having this problem

**Comment by dario-piotrowicz** [comment] 2024-10-01 17:37
Would anyone be able to provide a (hopefully minimal) reproduction for this error? that would be really really helpful 🙏

**Comment by blakeembrey** [comment] 2024-10-01 22:13
@dario-piotrowicz I was able to reproduce by upgrading next from a fresh init in a monorepo:

```sh
mkdir mono && cd mono
echo "{\"name\":\"mono\",\"workspaces\":[\"packages/*\"],\"private\":true,\"version\":\"0.0.0\",\"description\":\"\"}" > package.json
mkdir packages && cd packages
create-cloudflare test --framework=next --experimental
cd test
npm i next@latest
npm run deploy
```

**Comment by dario-piotrowicz** [comment] 2024-10-02 11:59
@blakeembrey thanks so much! with that I could reproduce the issue! 😄 

I've also found the solution, I've got to work on something unrelated for a bit, I'll open a PR with the fix later today 🙂👍

**Comment by dario-piotrowicz** [comment] 2024-10-02 17:09
The fix is on it's way! 😄

**Comment by fprl** [comment] 2024-10-02 18:01
Thank you a lot, next time I add a repro for sure!

**Comment by justindjeumenet** [comment] 2024-10-03 05:57
Hi guys!
I have the same configuration but the error comes on #patchCached:

# patchCached
file:///Users/justindjeumene/WebstormProjects/xxxxxxxxx/node_modules/@opennextjs/cloudflare/dist/cli/index.mjs:6860
    throw new Error("Cache patch not applied");
          ^
And **when I read your code below**, I do not know if this is coming from my side or your side:

// src/cli/build/patches/investigated/patch-cache.ts
import path7 from "node:path";
function patchCache(code, config) {
  console.log("# patchCached");
  const cacheHandler = path7.join(config.paths.internalPackage, "cli", "cache-handler.mjs");
  const patchedCode = code.replace(
    "const { cacheHandler } = this.nextConfig;",
    `const cacheHandler = null;
CacheHandler = (await import('${cacheHandler}')).default;
CacheHandler.maybeKVNamespace = process.env["${config.cache.kvBindingName}"];
`
  );
  if (patchedCode === code) {
    throw new Error("Cache patch not applied");
  }
  return patchedCode;
}

**Comment by dario-piotrowicz** [comment] 2024-10-03 09:13
@justindjeumenet what you're mentioning is a different bug could you please open a new issue for it? (ideally with a minimal reproduction 🙏)

**Closed** 2024-10-03 11:11 UTC

**Comment by dario-piotrowicz** [comment] 2024-10-03 11:18
@fprl it could be fixed now, if you want please try the latest release [`0.0.0-acc0c5e`](https://www.npmjs.com/package/@opennextjs/cloudflare/v/0.0.0-acc0c5e)

and let me know if it's all good now 🙂

**Comment by sorenhansendk** [comment] 2024-10-03 12:55
@dario-piotrowicz I have just tested with `0.0.0-acc0c5e` and I get this error now:

<pre>
# updateWebpackChunksFile
 - chunk 135.js
 - chunk 236.js
✘ [ERROR] Invalid alias name: "next/dist/compiled/ws"

✘ [ERROR] Invalid alias name: "next/dist/compiled/edge-runtime"

/{local-path-removed}/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 2 errors:
error: Invalid alias name: "next/dist/compiled/ws"
error: Invalid alias name: "next/dist/compiled/edge-runtime"
    at failureErrorWithLog (/Users/sorenhansen/Code/vivens-io/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/sorenhansen/Code/vivens-io/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/sorenhansen/Code/vivens-io/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/sorenhansen/Code/vivens-io/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/sorenhansen/Code/vivens-io/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/sorenhansen/Code/vivens-io/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/sorenhansen/Code/vivens-io/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/sorenhansen/Code/vivens-io/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Invalid alias name: "next/dist/compiled/ws"'
    },
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Invalid alias name: "next/dist/compiled/edge-runtime"'
    }
  ],
  warnings: []
}
</pre>

My scripts looks like this:

<pre>
"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "deploy": "cloudflare && wrangler deploy",
    "preview": "cloudflare && wrangler dev",
    "cf-typegen": "wrangler types --env-interface CloudflareEnv env.d.ts"
},
</pre>

And my dependencies looks like this:

<pre>
"devDependencies": {
    "@cloudflare/workers-types": "^4.20240925.0",
    "@opennextjs/cloudflare": "0.0.0-acc0c5e",
    "@types/node": "20.10.5",
    "@types/react": "18.2.45",
    "@types/react-dom": "18.2.18",
    "tailwindcss": "3.3.5",
    "tailwindcss-animate": "1.0.7",
    "eslint": "8.54.0",
    "eslint-config-next": "14.0.3",
    "@cloudflare/next-on-pages": "1.13.2",
    "elysia": "1.1.8",
    "wrangler": "^3.79.0"
}
</pre>

**Comment by VojGin** [comment] 2024-11-03 07:27
> @cloudflare/next-on-pages

I'm getting the same error even with the `@cloudflare/next-on-pages` package removed.

```
⚙️ Copying files...

# copyPrerenderedRoutes
# copyPackageTemplateFiles
⚙️ Bundling the worker file...

# patchWranglerDeps
# updateWebpackChunksFile
 - chunk 100.js
 - chunk 14.js
 - chunk 148.js
 - chunk 150.js
 - chunk 157.js
 - chunk 20.js
 - chunk 252.js
 - chunk 266.js
 - chunk 291.js
 - chunk 296.js
 - chunk 307.js
 - chunk 397.js
 - chunk 475.js
 - chunk 57.js
 - chunk 605.js
 - chunk 654.js
 - chunk 723.js
 - chunk 727.js
 - chunk 737.js
 - chunk 829.js
 - chunk 91.js
 - chunk 946.js
✘ [ERROR] Invalid alias name: "next/dist/compiled/ws"

✘ [ERROR] Invalid alias name: "next/dist/compiled/edge-runtime"

/Users/username/folder/project/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 2 errors:
error: Invalid alias name: "next/dist/compiled/ws"
error: Invalid alias name: "next/dist/compiled/edge-runtime"
    at failureErrorWithLog (/Users/username/folder/project/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/username/folder/project/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/username/folder/project/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/username/folder/project/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/username/folder/project/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/username/folder/project/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/username/folder/project/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/username/folder/project/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Invalid alias name: "next/dist/compiled/ws"'
    },
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Invalid alias name: "next/dist/compiled/edge-runtime"'
    }
  ],
  warnings: []
}

Node.js v20.17.0
error Command failed with exit code 1.
```

I'm on `next@14.2.16` and `@opennextjs/cloudflare@0.2.1`

**Comment by seivad** [comment] 2024-12-12 01:08
I get the same error as above after converting a project from next-on-pages to opennext, is there any solution?

```
✘ [ERROR] Invalid alias name: "next/dist/compiled/ws"

✘ [ERROR] Invalid alias name: "next/dist/compiled/edge-runtime"

/Users/mick/code/dashboard/node_modules/.pnpm/esbuild@0.15.18/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 2 errors:
error: Invalid alias name: "next/dist/compiled/ws"
error: Invalid alias name: "next/dist/compiled/edge-runtime"
```

**Comment by jsmestad** [comment] 2024-12-31 20:28
@seivad did you figure this error out?

**Comment by katis** [comment] 2025-01-28 06:48
@seivad @jsmestad @VojGin 

In my case this was caused by an old version of esbuild being installed in our monorepo. Adding

```
    "esbuild": "0.24.2",
```

To the Next.js package `package.json` fixed it

**Comment by jacobdcastro** [comment] 2025-01-31 22:02
I'm also getting the same error after converting from nextonpages -> opennext. `"esbuild": "0.24.2"` did not fix unfortunately. Any other suggestions?

**Comment by vicb** [comment] 2025-02-01 06:47
There is https://opennext.js.org/cloudflare/get-started#10-remove-cloudflarenext-on-pages-if-necessary, not sure if it helps ?
