### ISSUE TITLE
  ERROR  Error: Unsupported framework: next

### ISSUE THREAD

**Issue by nathanclevenger** [opennextjs/opennextjs-cloudflare#41] opened 2024-09-26 19:51 UTC
In following the instructions on the announcement blog post at https://blog.cloudflare.com/builder-day-2024-announcements/#cloudflare-joins-opennext running the command:
```bash
npm create cloudflare@latest -- my-next-app --framework=next --experimental
``` 
results in an error: `ERROR  Error: Unsupported framework: next`

create-cloudflare v2.28.1
Mac OS 15.1 Beta (24B5055e)
Node v20.13.1

Am I missing something obvious?  I'm going to dig into try to debug now, but since this is the command on the announcement post I wanted to log it here.

Thanks!

**Comment by dario-piotrowicz** [comment] 2024-09-27 11:15
@nathanclevenger thanks a lot for flagging this! ❤️ you're totally right it does not work 😓 

The problem is that we haven't yet actually released the latest C3 version 😓 

You can see that the command works in our beta release:
```
npm create cloudflare@beta -- my-next-app --framework=next --experimental
```
too bad that the command in the blog post does not actually work... we're tring to push for a C3 release to be made ASAP so that the command will work

**Comment by dario-piotrowicz** [comment] 2024-09-27 11:54
@nathanclevenger we've just cut a new release and the command should just now work (I've just tested it locally)

Hopefully it's all fine now, so I'm closing the issue, please feel free to reopen it if you think there's still a problem here

Again, thanks a lot for flagging this! 🚀

**Closed by dario-piotrowicz** 2024-09-27 11:54 UTC
