### ISSUE TITLE
commerce app fails with `Invalid URL: /api/2023-01/graphql.json` error

### ISSUE THREAD

**Issue by IgorMinar** [opennextjs/opennextjs-cloudflare#21] opened 2024-09-21 17:33 UTC
repro instructions:
```
pnpm create next-app@latest --example https://github.com/vercel/commerce
cd my-opennextjs-cloudflare-commerce-app
pnpm add -D wrangler @opennextjs/cloudflare

touch wrangler.toml
code wrangler.toml
```

insert:
```
#:schema node_modules/wrangler/config-schema.json
name = "opennextjs-cloudflare"
main = ".worker-next/index.mjs"


compatibility_date = "2024-08-29"
compatibility_flags = ["nodejs_compat_v2"]


# Use the new Workers + Assets to host the static frontend files
experimental_assets = { directory = ".worker-next/assets", binding = "ASSETS" }
```
and then
```
pnpm cloudflare
WRANGLER_BUILD_CONDITIONS="" WRANGLER_BUILD_PLATFORM="node" pnpm wrangler deploy
```

The app deploys (you need a paid account to be able to upload the >1MiB payload):
```
 ⛅️ wrangler 3.78.7
-------------------

🌀 Building list of assets...
🌀 Starting asset upload...
No files to upload. Proceeding with deployment...
Total Upload: 9577.17 KiB / gzip: 1789.06 KiB
Worker Startup Time: 48 ms
Uploaded opennextjs-cloudflare-commerce (8.72 sec)
Deployed opennextjs-cloudflare-commerce triggers (0.46 sec)
  https://opennextjs-cloudflare-commerce.swoosh.workers.dev
Current Version ID: ffc27398-0ea1-4070-a764-ee4ee9f30355
```

But then requests fail with:

<img width="1065" alt="Screenshot 2024-09-21 at 1 33 44 AM" src="https://github.com/user-attachments/assets/440ead54-ad5a-4285-9759-cdf9a88630bd">

and 

<img width="1129" alt="Screenshot 2024-09-21 at 1 33 29 AM" src="https://github.com/user-attachments/assets/c607d7cb-b0b3-4ac0-8f51-3efa75d1559c">

<details>
<summary>full wrangler tail log</summary>
GET https://opennextjs-cloudflare-commerce.swoosh.workers.dev/ - Ok @ 9/21/2024, 10:25:51 AM
  (log) readFile {
  path: '/.next/server/app/85981ba6a3364d424fe6a82f7ac16b5b795b03229b12556dafce8f1299d3f5c5.body'
}
  (log) readFile {
  path: '/.next/server/app/f9ec6465c9565d9ca0ed242af5e8e207310ea861134c3cc2c299f110fb605281.body'
}
  (log) readFile {
  path: '/.next/server/app/5dad47abef4b4220174efcd98846c1608a7cd1415b86cc209e9de441b51c1496.body'
}
  (log) readFile {
  path: '/.next/cache/fetch-cache/85981ba6a3364d424fe6a82f7ac16b5b795b03229b12556dafce8f1299d3f5c5',
  options: 'utf8'
}
  (log) readFile {
  path: '/.next/cache/fetch-cache/f9ec6465c9565d9ca0ed242af5e8e207310ea861134c3cc2c299f110fb605281',
  options: 'utf8'
}
  (log) readFile {
  path: '/.next/cache/fetch-cache/5dad47abef4b4220174efcd98846c1608a7cd1415b86cc209e9de441b51c1496',
  options: 'utf8'
}
  (log) readFile {
  path: '/.next/server/app/00d7e1359aabe9c228021188fc5d239970a02fba22bc30217837af09fb329c0f.body'
}
  (log) readFile {
  path: '/.next/cache/fetch-cache/00d7e1359aabe9c228021188fc5d239970a02fba22bc30217837af09fb329c0f',
  options: 'utf8'
}
  (log) CustomRequest /api/2023-01/graphql.json
  (log) CustomRequest /api/2023-01/graphql.json
  (log) CustomRequest /api/2023-01/graphql.json
  (log) CustomRequest /api/2023-01/graphql.json
  (error)  ⨯ {
  cause: 'unknown',
  status: 500,
  message: 'Invalid URL: /api/2023-01/graphql.json',
  query: '\n' +
    '  query getCollectionProducts(\n' +
    '    $handle: String!\n' +
    '    $sortKey: ProductCollectionSortKeys\n' +
    '    $reverse: Boolean\n' +
    '  ) {\n' +
    '    collection(handle: $handle) {\n' +
    '      products(sortKey: $sortKey, reverse: $reverse, first: 100) {\n' +
    '        edges {\n' +
    '          node {\n' +
    '            ...product\n' +
    '          }\n' +
    '        }\n' +
    '      }\n' +
    '    }\n' +
    '  }\n' +
    '  \n' +
    '  fragment product on Product {\n' +
    '    id\n' +
    '    handle\n' +
    '    availableForSale\n' +
    '    title\n' +
    '    description\n' +
    '    descriptionHtml\n' +
    '    options {\n' +
    '      id\n' +
    '      name\n' +
    '      values\n' +
    '    }\n' +
    '    priceRange {\n' +
    '      maxVariantPrice {\n' +
    '        amount\n' +
    '        currencyCode\n' +
    '      }\n' +
    '      minVariantPrice {\n' +
    '        amount\n' +
    '        currencyCode\n' +
    '      }\n' +
    '    }\n' +
    '    variants(first: 250) {\n' +
    '      edges {\n' +
    '        node {\n' +
    '          id\n' +
    '          title\n' +
    '          availableForSale\n' +
    '          selectedOptions {\n' +
    '            name\n' +
    '            value\n' +
    '          }\n' +
    '          price {\n' +
    '            amount\n' +
    '            currencyCode\n' +
    '          }\n' +
    '        }\n' +
    '      }\n' +
    '    }\n' +
    '    featuredImage {\n' +
    '      ...image\n' +
    '    }\n' +
    '    images(first: 20) {\n' +
    '      edges {\n' +
    '        node {\n' +
    '          ...image\n' +
    '        }\n' +
    '      }\n' +
    '    }\n' +
    '    seo {\n' +
    '      ...seo\n' +
    '    }\n' +
    '    tags\n' +
    '    updatedAt\n' +
    '  }\n' +
    '  \n' +
    '  fragment image on Image {\n' +
    '    url\n' +
    '    altText\n' +
    '    width\n' +
    '    height\n' +
    '  }\n' +
    '\n' +
    '  \n' +
    '  fragment seo on SEO {\n' +
    '    description\n' +
    '    title\n' +
    '  }\n' +
    '\n' +
    '\n',
  digest: '346390234'
}
  (error)  ⨯ {
  cause: 'unknown',
  status: 500,
  message: 'Invalid URL: /api/2023-01/graphql.json',
  query: '\n' +
    '  query getCollectionProducts(\n' +
    '    $handle: String!\n' +
    '    $sortKey: ProductCollectionSortKeys\n' +
    '    $reverse: Boolean\n' +
    '  ) {\n' +
    '    collection(handle: $handle) {\n' +
    '      products(sortKey: $sortKey, reverse: $reverse, first: 100) {\n' +
    '        edges {\n' +
    '          node {\n' +
    '            ...product\n' +
    '          }\n' +
    '        }\n' +
    '      }\n' +
    '    }\n' +
    '  }\n' +
    '  \n' +
    '  fragment product on Product {\n' +
    '    id\n' +
    '    handle\n' +
    '    availableForSale\n' +
    '    title\n' +
    '    description\n' +
    '    descriptionHtml\n' +
    '    options {\n' +
    '      id\n' +
    '      name\n' +
    '      values\n' +
    '    }\n' +
    '    priceRange {\n' +
    '      maxVariantPrice {\n' +
    '        amount\n' +
    '        currencyCode\n' +
    '      }\n' +
    '      minVariantPrice {\n' +
    '        amount\n' +
    '        currencyCode\n' +
    '      }\n' +
    '    }\n' +
    '    variants(first: 250) {\n' +
    '      edges {\n' +
    '        node {\n' +
    '          id\n' +
    '          title\n' +
    '          availableForSale\n' +
    '          selectedOptions {\n' +
    '            name\n' +
    '            value\n' +
    '          }\n' +
    '          price {\n' +
    '            amount\n' +
    '            currencyCode\n' +
    '          }\n' +
    '        }\n' +
    '      }\n' +
    '    }\n' +
    '    featuredImage {\n' +
    '      ...image\n' +
    '    }\n' +
    '    images(first: 20) {\n' +
    '      edges {\n' +
    '        node {\n' +
    '          ...image\n' +
    '        }\n' +
    '      }\n' +
    '    }\n' +
    '    seo {\n' +
    '      ...seo\n' +
    '    }\n' +
    '    tags\n' +
    '    updatedAt\n' +
    '  }\n' +
    '  \n' +
    '  fragment image on Image {\n' +
    '    url\n' +
    '    altText\n' +
    '    width\n' +
    '    height\n' +
    '  }\n' +
    '\n' +
    '  \n' +
    '  fragment seo on SEO {\n' +
    '    description\n' +
    '    title\n' +
    '  }\n' +
    '\n' +
    '\n',
  digest: '346390234'
}
  (error)  ⨯ {
  cause: 'unknown',
  status: 500,
  message: 'Invalid URL: /api/2023-01/graphql.json',
  query: '\n' +
    '  query getMenu($handle: String!) {\n' +
    '    menu(handle: $handle) {\n' +
    '      items {\n' +
    '        title\n' +
    '        url\n' +
    '      }\n' +
    '    }\n' +
    '  }\n',
  digest: '346390234'
}
  (error)  ⨯ {
  cause: 'unknown',
  status: 500,
  message: 'Invalid URL: /api/2023-01/graphql.json',
  query: '\n' +
    '  query getMenu($handle: String!) {\n' +
    '    menu(handle: $handle) {\n' +
    '      items {\n' +
    '        title\n' +
    '        url\n' +
    '      }\n' +
    '    }\n' +
    '  }\n',
  digest: '346390234'
}
  (error) headers already sent
GET https://opennextjs-cloudflare-commerce.swoosh.workers.dev/favicon.ico - Ok @ 9/21/2024, 10:25:52 AM
  (log) CustomRequest http://n/favicon.ico

</detail>

**Comment by vicb** [comment] 2024-09-23 06:22
`WRANGLER_BUILD_CONDITIONS="" WRANGLER_BUILD_PLATFORM="node"` is not required for the commerce app.

But you need 
1. A shopify store and set the corresponding env vars (`SHOPIFY_STORE_DOMAIN` and `SHOPIFY_STOREFRONT_ACCESS_TOKEN`)
2. A couple tweaks to remove some unsupported components - it should be possible to support them with some work.

I had created https://github.com/flarelabs-net/commerce/tree/builder with all the above changes.

**Comment by vicb** [comment] 2024-10-03 12:02
Closing this as the root cause what missing credentials.

The commerce app has been added the to [examples](https://github.com/opennextjs/opennextjs-cloudflare/tree/main/examples/vercel-commerce)

The solution is to add a `.dev.vars` based on the [example](https://github.com/opennextjs/opennextjs-cloudflare/blob/59a1d9e2526414d78bfc83ca2facbf8b12ecec1f/examples/vercel-commerce/.dev.vars.example) with a `SHOPIFY_STOREFRONT_ACCESS_TOKEN` and `SHOPIFY_STORE_DOMAIN`

**Closed by vicb** 2024-10-03 12:02 UTC
Labels: bug
