### ISSUE TITLE
Creating the app with bunx results in incomplete javascript code

### ISSUE THREAD

**Issue by justrach** [opennextjs/opennextjs-cloudflare#46] opened 2024-09-29 21:21 UTC
![image](https://github.com/user-attachments/assets/2e069255-3bd3-47a1-a1d6-59f297b54d2d)
Following the instructions on README.MD but by only using bunx instead of npx 

version:0.0.0-953d0b1

**Comment by dario-piotrowicz** [comment] 2024-09-30 11:01
Hi @justrach, thanks for the issue 🙂 

I could not reproduce this on my end up creating a brand new Next.js app

Could you share more details that can maybe help us reproduce this? Are you using a pre-existing Next.js application? (if so can you share it?) and/or could you share your app's code? also did you check if it works as intended with other package managers?

**Comment by vicb** [comment] 2024-10-09 19:42
Closing this issue because it's missing a repro.
@justrach feel free to re-open if you add a repro.
Thanks

**Closed by vicb** 2024-10-09 19:42 UTC
Labels: needs repro
